import {
  playClassicCareer,
  type ClassicChoicePolicy,
} from "../classicEngine";
import {
  CLASSIC_CATALOG,
  CLASSIC_CONTENT_VERSION,
} from "../catalog/classicCatalog";
import {
  deterministicHash,
  fnv1a64,
} from "../deterministicHash";
import { PACING_CONFIGS } from "../pacing";
import type { PacingMode } from "../pacing";
import {
  POSITION_ROLE_GROUPS,
  type ClassicPosition,
} from "../role";
import { ECONOMY_POLICY_VERSION } from "./economyPolicy";
import {
  MAX_OVERALL_PERCENTILE_TABLE,
  PERCENTILE_BENCHMARK_METADATA,
} from "./percentileTable.generated";

export const PERCENTILE_BENCHMARK_VERSION =
  "2026-07-31-max-overall-v1" as const;
export const PERCENTILE_BENCHMARK_SAMPLE_COUNT =
  10_000 as const;
export const PERCENTILE_BENCHMARK_SEED =
  "football-life-reborn:percentile:v1" as const;
export const PERCENTILE_BENCHMARK_STRATEGY =
  "fnv1a64-uniform-valid-option-v1" as const;

const BENCHMARK_POSITIONS = Object.freeze(
  Object.values(POSITION_ROLE_GROUPS).flat(),
) as readonly ClassicPosition[];
const BENCHMARK_MODES = Object.freeze(
  Object.keys(PACING_CONFIGS),
) as readonly PacingMode[];

export type PercentileBenchmarkMetadata = {
  readonly artifactHash: string;
  readonly contentVersion: string;
  readonly countryCount: number;
  readonly economyPolicyVersion: string;
  readonly modeCount: number;
  readonly positionCount: number;
  readonly sampleCount: number;
  readonly seed: string;
  readonly strategy: string;
  readonly version: string;
};

export type PercentileBenchmarkArtifact = {
  readonly maxOverallPercentiles: readonly number[];
  readonly metadata: PercentileBenchmarkMetadata;
};

export function generatePercentileBenchmark(): PercentileBenchmarkArtifact {
  const maxOverallValues = Array.from(
    { length: PERCENTILE_BENCHMARK_SAMPLE_COUNT },
    (_, sampleIndex) => simulateBenchmarkCareer(sampleIndex),
  ).sort((left, right) => left - right);
  const maxOverallPercentiles = Object.freeze(
    Array.from({ length: 100 }, (_, index) => {
      const rank = Math.ceil(
        ((index + 1) *
          PERCENTILE_BENCHMARK_SAMPLE_COUNT) /
          100,
      );
      return maxOverallValues[rank - 1]!;
    }),
  );
  const metadataWithoutHash = Object.freeze({
    contentVersion: CLASSIC_CONTENT_VERSION,
    countryCount: CLASSIC_CATALOG.countries.length,
    economyPolicyVersion: ECONOMY_POLICY_VERSION,
    modeCount: BENCHMARK_MODES.length,
    positionCount: BENCHMARK_POSITIONS.length,
    sampleCount: PERCENTILE_BENCHMARK_SAMPLE_COUNT,
    seed: PERCENTILE_BENCHMARK_SEED,
    strategy: PERCENTILE_BENCHMARK_STRATEGY,
    version: PERCENTILE_BENCHMARK_VERSION,
  });
  const metadata = Object.freeze({
    artifactHash: deterministicHash({
      maxOverallPercentiles,
      metadata: metadataWithoutHash,
    }),
    ...metadataWithoutHash,
  });

  return Object.freeze({
    maxOverallPercentiles,
    metadata,
  });
}

export function calculateSimulatedCareerPercentile(
  maxOverall: number,
  table: readonly number[] =
    MAX_OVERALL_PERCENTILE_TABLE,
): number {
  if (
    !Number.isInteger(maxOverall) ||
    maxOverall < 40 ||
    maxOverall > 99
  ) {
    throw new RangeError(
      `Max Overall must be an integer from 40 to 99: ${maxOverall}`,
    );
  }

  if (
    table.length !== 100 ||
    table.some(
      (threshold, index) =>
        !Number.isInteger(threshold) ||
        threshold < 40 ||
        threshold > 99 ||
        (index > 0 && threshold < table[index - 1]!),
    )
  ) {
    throw new RangeError(
      "Simulated career percentile table is invalid",
    );
  }

  let percentile = 0;

  for (const threshold of table) {
    if (threshold > maxOverall) {
      break;
    }
    percentile += 1;
  }

  return percentile;
}

export function generatedPercentileBenchmark(): PercentileBenchmarkArtifact {
  return Object.freeze({
    maxOverallPercentiles:
      MAX_OVERALL_PERCENTILE_TABLE,
    metadata: PERCENTILE_BENCHMARK_METADATA,
  });
}

export function serializePercentileBenchmark(
  artifact: PercentileBenchmarkArtifact,
): string {
  return `// Generated by \`npm run generate:benchmark\`. Do not edit manually.
export const MAX_OVERALL_PERCENTILE_TABLE = Object.freeze(
${indentJson(artifact.maxOverallPercentiles)} as readonly number[],
);

export const PERCENTILE_BENCHMARK_METADATA = Object.freeze(
${indentJson(artifact.metadata)},
);
`;
}

function indentJson(value: unknown): string {
  return JSON.stringify(value, null, 2)
    .split("\n")
    .map((line) => `  ${line}`)
    .join("\n");
}

function simulateBenchmarkCareer(sampleIndex: number): number {
  const country =
    CLASSIC_CATALOG.countries[
      sampleIndex % CLASSIC_CATALOG.countries.length
    ]!;
  const position =
    BENCHMARK_POSITIONS[
      Math.floor(
        sampleIndex / CLASSIC_CATALOG.countries.length,
      ) % BENCHMARK_POSITIONS.length
    ]!;
  const mode =
    BENCHMARK_MODES[
      Math.floor(
        sampleIndex /
          (CLASSIC_CATALOG.countries.length *
            BENCHMARK_POSITIONS.length),
      ) % BENCHMARK_MODES.length
    ]!;
  const seed = [
    PERCENTILE_BENCHMARK_SEED,
    sampleIndex,
    country.fifaCode,
    position,
    mode,
  ].join(":");
  const policy: ClassicChoicePolicy = (
    state,
    decision,
  ) => {
    const choiceHash = fnv1a64(
      [
        PERCENTILE_BENCHMARK_STRATEGY,
        sampleIndex,
        state.choiceCursor,
        decision.id,
      ].join(":"),
    );
    const optionIndex =
      Number.parseInt(choiceHash.slice(-8), 16) %
      decision.options.length;

    return decision.options[optionIndex]!.id;
  };
  const career = playClassicCareer({
    identity: {
      lastName: "模拟",
      nationalityFifaCode: country.fifaCode,
      position,
      preferredNumber:
        position === "GK" ? 1 : (sampleIndex % 99) + 1,
    },
    mode,
    policy,
    seed,
  });

  return career.summary!.maxOverall;
}
